const { Post } = require('../models');

const postData = [
  {
    title: 'Montezuma',
    post_body: `I have printed it out, but the animated gif is not moving, so what is a hamburger menu. We need to make the new version clean and sexy we try your eye, but can you change everything? thanks for taking the time to make the website, but i already made it in wix. We don't need a backup, it never goes down! make it pop but the website doesn't have the theme i was going for we are a startup, but try making it a bit less blah. Concept is bang on, but can we look at a better execution. Submit your meaningless business jargon to be used on the site! I got your invoice...it seems really high, why did you charge so much, can it handle a million in one go this red is too red, there is too much white space labrador. The animation does not work, when i print the page we try your eye, but can you change everything? the website doesn't have the theme i was going for. Is there a way we can make the page feel more introductory without being cheesy start on it today and we will talk about what i want next time and can you make it pop, nor can you make the blue bluer? can it handle a million in one go. Pass the mayo, appeal to the client, sue the vice president this is just a 5 minutes job. Can you make it pop we are a non-profit organization, and we are a startup, or do less with more. Jazz it up a little is this the best we can do. There are more projects lined up charge extra the next time why is a 15mb gif on the startpage a bad idea?!, thanks for taking the time to make the website, but i already made it in wix, thats not what i saw in my head at all nor I really like the colour but can you change it.`,
    user_id: 1,
  },
  {
    title: 'Goober',
    post_body: `I have printed it out, but the animated gif is not moving, so what is a hamburger menu. We need to make the new version clean and sexy we try your eye, but can you change everything? thanks for taking the time to make the website, but i already made it in wix. We don't need a backup, it never goes down! make it pop but the website doesn't have the theme i was going for we are a startup, but try making it a bit less blah. Concept is bang on, but can we look at a better execution. Submit your meaningless business jargon to be used on the site! I got your invoice...it seems really high, why did you charge so much, can it handle a million in one go this red is too red, there is too much white space labrador. The animation does not work, when i print the page we try your eye, but can you change everything? the website doesn't have the theme i was going for. Is there a way we can make the page feel more introductory without being cheesy start on it today and we will talk about what i want next time and can you make it pop, nor can you make the blue bluer? can it handle a million in one go. Pass the mayo, appeal to the client, sue the vice president this is just a 5 minutes job. Can you make it pop we are a non-profit organization, and we are a startup, or do less with more. Jazz it up a little is this the best we can do. There are more projects lined up charge extra the next time why is a 15mb gif on the startpage a bad idea?!, thanks for taking the time to make the website, but i already made it in wix, thats not what i saw in my head at all nor I really like the colour but can you change it.`,
    user_id: 2,
  },
  {
    title: 'CUBA',
    post_body: `I have printed it out, but the animated gif is not moving, so what is a hamburger menu. We need to make the new version clean and sexy we try your eye, but can you change everything? thanks for taking the time to make the website, but i already made it in wix. We don't need a backup, it never goes down! make it pop but the website doesn't have the theme i was going for we are a startup, but try making it a bit less blah. Concept is bang on, but can we look at a better execution. Submit your meaningless business jargon to be used on the site! I got your invoice...it seems really high, why did you charge so much, can it handle a million in one go this red is too red, there is too much white space labrador. The animation does not work, when i print the page we try your eye, but can you change everything? the website doesn't have the theme i was going for. Is there a way we can make the page feel more introductory without being cheesy start on it today and we will talk about what i want next time and can you make it pop, nor can you make the blue bluer? can it handle a million in one go. Pass the mayo, appeal to the client, sue the vice president this is just a 5 minutes job. Can you make it pop we are a non-profit organization, and we are a startup, or do less with more. Jazz it up a little is this the best we can do. There are more projects lined up charge extra the next time why is a 15mb gif on the startpage a bad idea?!, thanks for taking the time to make the website, but i already made it in wix, thats not what i saw in my head at all nor I really like the colour but can you change it.`,
    user_id: 3,
  },
  {
    title: 'Star Wars',
    post_body: `I have printed it out, but the animated gif is not moving, so what is a hamburger menu. We need to make the new version clean and sexy we try your eye, but can you change everything? thanks for taking the time to make the website, but i already made it in wix. We don't need a backup, it never goes down! make it pop but the website doesn't have the theme i was going for we are a startup, but try making it a bit less blah. Concept is bang on, but can we look at a better execution. Submit your meaningless business jargon to be used on the site! I got your invoice...it seems really high, why did you charge so much, can it handle a million in one go this red is too red, there is too much white space labrador. The animation does not work, when i print the page we try your eye, but can you change everything? the website doesn't have the theme i was going for. Is there a way we can make the page feel more introductory without being cheesy start on it today and we will talk about what i want next time and can you make it pop, nor can you make the blue bluer? can it handle a million in one go. Pass the mayo, appeal to the client, sue the vice president this is just a 5 minutes job. Can you make it pop we are a non-profit organization, and we are a startup, or do less with more. Jazz it up a little is this the best we can do. There are more projects lined up charge extra the next time why is a 15mb gif on the startpage a bad idea?!, thanks for taking the time to make the website, but i already made it in wix, thats not what i saw in my head at all nor I really like the colour but can you change it.`,
    user_id: 4,
  },
  {
    title: 'Krishna',
    post_body: `I have printed it out, but the animated gif is not moving, so what is a hamburger menu. We need to make the new version clean and sexy we try your eye, but can you change everything? thanks for taking the time to make the website, but i already made it in wix. We don't need a backup, it never goes down! make it pop but the website doesn't have the theme i was going for we are a startup, but try making it a bit less blah. Concept is bang on, but can we look at a better execution. Submit your meaningless business jargon to be used on the site! I got your invoice...it seems really high, why did you charge so much, can it handle a million in one go this red is too red, there is too much white space labrador. The animation does not work, when i print the page we try your eye, but can you change everything? the website doesn't have the theme i was going for. Is there a way we can make the page feel more introductory without being cheesy start on it today and we will talk about what i want next time and can you make it pop, nor can you make the blue bluer? can it handle a million in one go. Pass the mayo, appeal to the client, sue the vice president this is just a 5 minutes job. Can you make it pop we are a non-profit organization, and we are a startup, or do less with more. Jazz it up a little is this the best we can do. There are more projects lined up charge extra the next time why is a 15mb gif on the startpage a bad idea?!, thanks for taking the time to make the website, but i already made it in wix, thats not what i saw in my head at all nor I really like the colour but can you change it.`,
    user_id: 5,
  },
];

const seedPosts = () => Post.bulkCreate(postData);

module.exports = seedPosts;
